export const tokens = {
  sprout: {
    colorPrimary: "#0f5238",
    colorPrimaryRgb: "15, 82, 56",
    colorPrimaryContainer: "#2d6a4f",
    colorOnPrimary: "#ffffff",
    colorSecondary: "#1f6d1a",
    colorSecondaryContainer: "#a4f792",
    colorTertiary: "#621cab",
    colorTertiaryContainer: "#7b3cc4",
    colorOnTertiary: "#ffffff",
    colorSurface: "#fefae8",
    colorSurfaceDim: "#dedaca",
    colorSurfaceContainer: "#f2eedd",
    colorSurfaceContainerLow: "#f8f4e3",
    colorSurfaceContainerHigh: "#ece8d8",
    colorOnSurface: "#1d1c12",
    colorOnSurfaceVariant: "#344039",
    colorOutline: "#707973",
    colorOutlineVariant: "#bfc9c1",
    colorError: "#ba1a1a",
    colorAccentGold: "#f4c95d",
  },
  midnight: {
    colorPrimary: "#84a98c",
    colorPrimaryRgb: "132, 169, 140",
    colorPrimaryContainer: "#52796f",
    colorOnPrimary: "#1a2421",
    colorSecondary: "#cad2c5",
    colorSecondaryContainer: "#84a98c",
    colorTertiary: "#354f52",
    colorTertiaryContainer: "#2f3e46",
    colorOnTertiary: "#cad2c5",
    colorSurface: "#1a2421",
    colorSurfaceDim: "#1a2421",
    colorSurfaceContainer: "#2f3e46",
    colorSurfaceContainerLow: "#202a25",
    colorSurfaceContainerHigh: "#354f52",
    colorOnSurface: "#cad2c5",
    colorOnSurfaceVariant: "#a8c7ad",
    colorOutline: "#52796f",
    colorOutlineVariant: "#354f52",
    colorError: "#ffb4ab",
    colorAccentGold: "#ffe099",
  },
  // Store-unlockable: "Autumn Canopy Theme" -- warm amber/terracotta forest light
  autumn: {
    colorPrimary: "#a8551b",
    colorPrimaryRgb: "168, 85, 27",
    colorPrimaryContainer: "#d97b3f",
    colorOnPrimary: "#ffffff",
    colorSecondary: "#7c4a1e",
    colorSecondaryContainer: "#f0c294",
    colorTertiary: "#8a3b12",
    colorTertiaryContainer: "#c1621f",
    colorOnTertiary: "#ffffff",
    colorSurface: "#fdf1e3",
    colorSurfaceDim: "#e8d3b8",
    colorSurfaceContainer: "#f5e3cc",
    colorSurfaceContainerLow: "#faeddb",
    colorSurfaceContainerHigh: "#efdcc0",
    colorOnSurface: "#2e1d0f",
    colorOnSurfaceVariant: "#6b4b2f",
    colorOutline: "#8a7259",
    colorOutlineVariant: "#d4c0a3",
    colorError: "#ba1a1a",
    colorAccentGold: "#e0a840",
  },
  // Store-unlockable: "Ocean Trench Theme" -- deep-sea dark teal/cyan
  ocean: {
    colorPrimary: "#3fd0c9",
    colorPrimaryRgb: "63, 208, 201",
    colorPrimaryContainer: "#1f7a75",
    colorOnPrimary: "#022826",
    colorSecondary: "#8fd6e8",
    colorSecondaryContainer: "#1e5866",
    colorTertiary: "#4a6fa5",
    colorTertiaryContainer: "#2c4670",
    colorOnTertiary: "#eaf2ff",
    colorSurface: "#071a22",
    colorSurfaceDim: "#071a22",
    colorSurfaceContainer: "#0f2933",
    colorSurfaceContainerLow: "#0a212a",
    colorSurfaceContainerHigh: "#163542",
    colorOnSurface: "#d3ecf2",
    colorOnSurfaceVariant: "#9ed4dd",
    colorOutline: "#3d6875",
    colorOutlineVariant: "#1c3944",
    colorError: "#ffb4ab",
    colorAccentGold: "#7fe8d4",
  },
};

export type ThemeTokenKey = keyof typeof tokens;
