export const tokens = {
  sprout: {
    colorPrimary: "#0f5238",
    colorPrimaryRgb: "15, 82, 56",
    colorPrimaryContainer: "#2d6a4f",
    colorOnPrimary: "#ffffff",
    colorSecondary: "#1f6d1a",
    colorSecondaryContainer: "#a4f792",
    colorTertiary: "#621cab",
    colorTertiaryContainer: "#7b3cc4",
    colorOnTertiary: "#ffffff",
    colorSurface: "#fefae8",
    colorSurfaceDim: "#dedaca",
    colorSurfaceContainer: "#f2eedd",
    colorSurfaceContainerLow: "#f8f4e3",
    colorSurfaceContainerHigh: "#ece8d8",
    colorOnSurface: "#1d1c12",
    colorOnSurfaceVariant: "#404943",
    colorOutline: "#707973",
    colorOutlineVariant: "#bfc9c1",
    colorError: "#ba1a1a",
    colorAccentGold: "#f4c95d",
  },
  midnight: {
    colorPrimary: "#00e479",
    colorPrimaryRgb: "0, 228, 121",
    colorPrimaryContainer: "#00ff88",
    colorOnPrimary: "#003919",
    colorSecondary: "#ecb1ff",
    colorSecondaryContainer: "#d05bff",
    colorTertiary: "#fefafa",
    colorTertiaryContainer: "#e1dedd",
    colorOnTertiary: "#313030",
    colorSurface: "#131313",
    colorSurfaceDim: "#131313",
    colorSurfaceContainer: "#20201f",
    colorSurfaceContainerLow: "#1c1b1b",
    colorSurfaceContainerHigh: "#2a2a2a",
    colorOnSurface: "#e5e2e1",
    colorOnSurfaceVariant: "#b9cbb9",
    colorOutline: "#849585",
    colorOutlineVariant: "#3b4b3d",
    colorError: "#ffb4ab",
    colorAccentGold: "#ffe099",
  },
};
