#!/usr/bin/env python3
"""Generate src-tauri/src/dictionary.rs and public/dictionary.json from the
ENABLE word list under data/dictionary/enable1.txt, minus anything in
data/dictionary/blocklist.txt -- same parity-generation pattern as
gen_categories.py. See data/dictionary/CREDITS.md for word list provenance.

Length bounds match what the game can actually use: MIN_LEN mirrors the
category word-length floor, MAX_LEN mirrors the largest grid (10x10) --
nothing longer can ever be dragged out, so longer entries are dead weight.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "data" / "dictionary"
RUST_OUT = ROOT / "src-tauri" / "src" / "dictionary.rs"
JSON_OUT = ROOT / "public" / "dictionary.json"

MIN_LEN = 3
MAX_LEN = 10


def main():
    blocklist = set()
    for line in (DATA_DIR / "blocklist.txt").read_text().splitlines():
        w = line.strip()
        if w:
            blocklist.add(w.upper())

    words = set()
    for line in (DATA_DIR / "enable1.txt").read_text().splitlines():
        w = line.strip().upper()
        if MIN_LEN <= len(w) <= MAX_LEN and w.isalpha():
            words.add(w)

    words -= blocklist
    out_words = sorted(words)

    with RUST_OUT.open("w") as f:
        f.write("// Generated by scripts/gen_dictionary.py -- do not hand-edit.\n")
        f.write("pub static DICTIONARY: &[&str] = &[\n")
        for w in out_words:
            f.write(f'    "{w}",\n')
        f.write("];\n")

    with JSON_OUT.open("w") as f:
        json.dump(out_words, f)

    print(f"{len(out_words)} words -> {RUST_OUT}, {JSON_OUT}")


if __name__ == "__main__":
    main()
