// Generated by scripts/gen_categories.py -- do not hand-edit.

mod animals;
mod card_games;
mod colors;
mod countries;
mod dance_styles;
mod desserts;
mod emotions;
mod food;
mod fruits;
mod gardening;
mod holidays;
mod horror_themes;
mod household;
mod insects;
mod kitchen_items;
mod movies_tv;
mod musical_genres;
mod musical_instruments;
mod mythical_creatures;
mod nature;
mod occupations;
mod ocean_life;
mod school_subjects;
mod space_astronomy;
mod sports;
mod tools;
mod vehicles;
mod weather;
mod architecture;
mod astrology_zodiac;
mod chemistry;
mod cooking_techniques;
mod cryptic_adjectives;
mod etymology_word_roots;
mod forensics;
mod geology_minerals;
mod grammar_linguistics;
mod legal_terms;
mod medical_terminology;
mod mycology;
mod nautical_terms;
mod philosophy;
mod types_of_government;
mod weaving_textiles;

#[derive(Clone, Copy, PartialEq, Eq, serde::Serialize)]
#[serde(rename_all = "lowercase")]
pub enum Tier {
    Standard,
    Challenging,
}

pub struct Category {
    pub name: &'static str,
    pub tier: Tier,
    pub words: &'static [&'static str],
}

pub static CATEGORIES: &[Category] = &[
    Category { name: "Animals", tier: Tier::Standard, words: animals::WORDS },
    Category { name: "Card Games", tier: Tier::Standard, words: card_games::WORDS },
    Category { name: "Colors", tier: Tier::Standard, words: colors::WORDS },
    Category { name: "Countries", tier: Tier::Standard, words: countries::WORDS },
    Category { name: "Dance Styles", tier: Tier::Standard, words: dance_styles::WORDS },
    Category { name: "Desserts", tier: Tier::Standard, words: desserts::WORDS },
    Category { name: "Emotions", tier: Tier::Standard, words: emotions::WORDS },
    Category { name: "Food", tier: Tier::Standard, words: food::WORDS },
    Category { name: "Fruits", tier: Tier::Standard, words: fruits::WORDS },
    Category { name: "Gardening", tier: Tier::Standard, words: gardening::WORDS },
    Category { name: "Holidays", tier: Tier::Standard, words: holidays::WORDS },
    Category { name: "Horror Themes", tier: Tier::Standard, words: horror_themes::WORDS },
    Category { name: "Household", tier: Tier::Standard, words: household::WORDS },
    Category { name: "Insects", tier: Tier::Standard, words: insects::WORDS },
    Category { name: "Kitchen Items", tier: Tier::Standard, words: kitchen_items::WORDS },
    Category { name: "Movies & TV", tier: Tier::Standard, words: movies_tv::WORDS },
    Category { name: "Musical Genres", tier: Tier::Standard, words: musical_genres::WORDS },
    Category { name: "Musical Instruments", tier: Tier::Standard, words: musical_instruments::WORDS },
    Category { name: "Mythical Creatures", tier: Tier::Standard, words: mythical_creatures::WORDS },
    Category { name: "Nature", tier: Tier::Standard, words: nature::WORDS },
    Category { name: "Occupations", tier: Tier::Standard, words: occupations::WORDS },
    Category { name: "Ocean Life", tier: Tier::Standard, words: ocean_life::WORDS },
    Category { name: "School Subjects", tier: Tier::Standard, words: school_subjects::WORDS },
    Category { name: "Space & Astronomy", tier: Tier::Standard, words: space_astronomy::WORDS },
    Category { name: "Sports", tier: Tier::Standard, words: sports::WORDS },
    Category { name: "Tools", tier: Tier::Standard, words: tools::WORDS },
    Category { name: "Vehicles", tier: Tier::Standard, words: vehicles::WORDS },
    Category { name: "Weather", tier: Tier::Standard, words: weather::WORDS },
    Category { name: "Architecture", tier: Tier::Challenging, words: architecture::WORDS },
    Category { name: "Astrology/Zodiac", tier: Tier::Challenging, words: astrology_zodiac::WORDS },
    Category { name: "Chemistry Elements/Terms", tier: Tier::Challenging, words: chemistry::WORDS },
    Category { name: "Cooking Techniques", tier: Tier::Challenging, words: cooking_techniques::WORDS },
    Category { name: "Cryptic/Obscure Adjectives", tier: Tier::Challenging, words: cryptic_adjectives::WORDS },
    Category { name: "Etymology/Word Roots", tier: Tier::Challenging, words: etymology_word_roots::WORDS },
    Category { name: "Forensics", tier: Tier::Challenging, words: forensics::WORDS },
    Category { name: "Geology/Minerals", tier: Tier::Challenging, words: geology_minerals::WORDS },
    Category { name: "Grammar/Linguistics", tier: Tier::Challenging, words: grammar_linguistics::WORDS },
    Category { name: "Legal Terms", tier: Tier::Challenging, words: legal_terms::WORDS },
    Category { name: "Medical Terminology", tier: Tier::Challenging, words: medical_terminology::WORDS },
    Category { name: "Mycology (Fungi)", tier: Tier::Challenging, words: mycology::WORDS },
    Category { name: "Nautical Terms", tier: Tier::Challenging, words: nautical_terms::WORDS },
    Category { name: "Philosophy", tier: Tier::Challenging, words: philosophy::WORDS },
    Category { name: "Types of Government", tier: Tier::Challenging, words: types_of_government::WORDS },
    Category { name: "Weaving/Textiles", tier: Tier::Challenging, words: weaving_textiles::WORDS },
];
