// Generated by scripts/gen_categories.py -- do not hand-edit.

mod baby_animals;
mod bathroom;
mod bedroom;
mod body_parts;
mod breakfast;
mod bugs;
mod calendar;
mod clothing;
mod drinks;
mod family;
mod farm_animals;
mod numbers;
mod pets;
mod picnic;
mod playground;
mod school_supplies;
mod seasons;
mod shapes;
mod transportation;
mod zoo_animals;
mod action_adventure;
mod animals;
mod anime_manga;
mod baking;
mod beach_summer;
mod birds;
mod board_games;
mod camping;
mod card_games;
mod circus;
mod cities;
mod colors;
mod comedy;
mod countries;
mod county_fair;
mod crime_noir;
mod dance_styles;
mod desserts;
mod emotions;
mod fairy_tales;
mod fantasy;
mod farm_life;
mod food;
mod fruits;
mod gardening;
mod holidays;
mod horror_themes;
mod household;
mod insects;
mod kitchen_items;
mod knights_castles;
mod lakes;
mod movies_tv;
mod musical_genres;
mod musical_instruments;
mod musicals;
mod mystery_thriller;
mod mythical_creatures;
mod nature;
mod occupations;
mod ocean_life;
mod photography;
mod pirates;
mod renfest;
mod romance;
mod school_subjects;
mod sci_fi;
mod space_astronomy;
mod sports;
mod superheroes;
mod the_zoo;
mod tools;
mod toys;
mod vehicles;
mod video_games;
mod war_films;
mod weather;
mod weddings;
mod western;
mod world_events;
mod anatomy;
mod archaeology;
mod architecture;
mod astrology_zodiac;
mod business;
mod chemistry;
mod computer_science;
mod computers;
mod cooking_techniques;
mod corporate_life;
mod cryptic_adjectives;
mod cryptography;
mod economics_finance;
mod etymology_word_roots;
mod forensics;
mod geology_minerals;
mod grammar_linguistics;
mod heraldry;
mod history;
mod legal_terms;
mod literary_devices;
mod medical_terminology;
mod music_theory;
mod mycology;
mod mythology;
mod nautical_terms;
mod paleontology;
mod philosophy;
mod physics;
mod psychology;
mod trades;
mod types_of_government;
mod weaving_textiles;

#[derive(Clone, Copy, PartialEq, Eq, serde::Serialize)]
#[serde(rename_all = "lowercase")]
pub enum Tier {
    Easy,
    Standard,
    Challenging,
}

pub struct Category {
    pub name: &'static str,
    pub tier: Tier,
    pub words: &'static [&'static str],
}

pub static CATEGORIES: &[Category] = &[
    Category { name: "Baby Animals", tier: Tier::Easy, words: baby_animals::WORDS },
    Category { name: "Bathroom Items", tier: Tier::Easy, words: bathroom::WORDS },
    Category { name: "Bedroom Items", tier: Tier::Easy, words: bedroom::WORDS },
    Category { name: "Body Parts", tier: Tier::Easy, words: body_parts::WORDS },
    Category { name: "Breakfast Foods", tier: Tier::Easy, words: breakfast::WORDS },
    Category { name: "Bugs", tier: Tier::Easy, words: bugs::WORDS },
    Category { name: "Days & Months", tier: Tier::Easy, words: calendar::WORDS },
    Category { name: "Clothing", tier: Tier::Easy, words: clothing::WORDS },
    Category { name: "Drinks", tier: Tier::Easy, words: drinks::WORDS },
    Category { name: "Family", tier: Tier::Easy, words: family::WORDS },
    Category { name: "Farm Animals", tier: Tier::Easy, words: farm_animals::WORDS },
    Category { name: "Numbers", tier: Tier::Easy, words: numbers::WORDS },
    Category { name: "Pets", tier: Tier::Easy, words: pets::WORDS },
    Category { name: "Picnic", tier: Tier::Easy, words: picnic::WORDS },
    Category { name: "Playground", tier: Tier::Easy, words: playground::WORDS },
    Category { name: "School Supplies", tier: Tier::Easy, words: school_supplies::WORDS },
    Category { name: "Seasons", tier: Tier::Easy, words: seasons::WORDS },
    Category { name: "Shapes", tier: Tier::Easy, words: shapes::WORDS },
    Category { name: "Transportation", tier: Tier::Easy, words: transportation::WORDS },
    Category { name: "Zoo Animals", tier: Tier::Easy, words: zoo_animals::WORDS },
    Category { name: "Action & Adventure", tier: Tier::Standard, words: action_adventure::WORDS },
    Category { name: "Animals", tier: Tier::Standard, words: animals::WORDS },
    Category { name: "Anime & Manga", tier: Tier::Standard, words: anime_manga::WORDS },
    Category { name: "Baking", tier: Tier::Standard, words: baking::WORDS },
    Category { name: "Beach & Summer", tier: Tier::Standard, words: beach_summer::WORDS },
    Category { name: "Birds", tier: Tier::Standard, words: birds::WORDS },
    Category { name: "Board Games", tier: Tier::Standard, words: board_games::WORDS },
    Category { name: "Camping & Outdoors", tier: Tier::Standard, words: camping::WORDS },
    Category { name: "Card Games", tier: Tier::Standard, words: card_games::WORDS },
    Category { name: "Circus & Carnival", tier: Tier::Standard, words: circus::WORDS },
    Category { name: "Cities", tier: Tier::Standard, words: cities::WORDS },
    Category { name: "Colors", tier: Tier::Standard, words: colors::WORDS },
    Category { name: "Comedy", tier: Tier::Standard, words: comedy::WORDS },
    Category { name: "Countries", tier: Tier::Standard, words: countries::WORDS },
    Category { name: "County Fair", tier: Tier::Standard, words: county_fair::WORDS },
    Category { name: "Crime & Noir", tier: Tier::Standard, words: crime_noir::WORDS },
    Category { name: "Dance Styles", tier: Tier::Standard, words: dance_styles::WORDS },
    Category { name: "Desserts", tier: Tier::Standard, words: desserts::WORDS },
    Category { name: "Emotions", tier: Tier::Standard, words: emotions::WORDS },
    Category { name: "Fairy Tales", tier: Tier::Standard, words: fairy_tales::WORDS },
    Category { name: "Fantasy", tier: Tier::Standard, words: fantasy::WORDS },
    Category { name: "Farm Life", tier: Tier::Standard, words: farm_life::WORDS },
    Category { name: "Food", tier: Tier::Standard, words: food::WORDS },
    Category { name: "Fruits", tier: Tier::Standard, words: fruits::WORDS },
    Category { name: "Gardening", tier: Tier::Standard, words: gardening::WORDS },
    Category { name: "Holidays", tier: Tier::Standard, words: holidays::WORDS },
    Category { name: "Horror Themes", tier: Tier::Standard, words: horror_themes::WORDS },
    Category { name: "Household", tier: Tier::Standard, words: household::WORDS },
    Category { name: "Insects", tier: Tier::Standard, words: insects::WORDS },
    Category { name: "Kitchen Items", tier: Tier::Standard, words: kitchen_items::WORDS },
    Category { name: "Knights & Castles", tier: Tier::Standard, words: knights_castles::WORDS },
    Category { name: "Lakes", tier: Tier::Standard, words: lakes::WORDS },
    Category { name: "Movies & TV", tier: Tier::Standard, words: movies_tv::WORDS },
    Category { name: "Musical Genres", tier: Tier::Standard, words: musical_genres::WORDS },
    Category { name: "Musical Instruments", tier: Tier::Standard, words: musical_instruments::WORDS },
    Category { name: "Musicals", tier: Tier::Standard, words: musicals::WORDS },
    Category { name: "Mystery & Thriller", tier: Tier::Standard, words: mystery_thriller::WORDS },
    Category { name: "Mythical Creatures", tier: Tier::Standard, words: mythical_creatures::WORDS },
    Category { name: "Nature", tier: Tier::Standard, words: nature::WORDS },
    Category { name: "Occupations", tier: Tier::Standard, words: occupations::WORDS },
    Category { name: "Ocean Life", tier: Tier::Standard, words: ocean_life::WORDS },
    Category { name: "Photography", tier: Tier::Standard, words: photography::WORDS },
    Category { name: "Pirates", tier: Tier::Standard, words: pirates::WORDS },
    Category { name: "Renaissance Festival", tier: Tier::Standard, words: renfest::WORDS },
    Category { name: "Romance", tier: Tier::Standard, words: romance::WORDS },
    Category { name: "School Subjects", tier: Tier::Standard, words: school_subjects::WORDS },
    Category { name: "Sci-Fi", tier: Tier::Standard, words: sci_fi::WORDS },
    Category { name: "Space & Astronomy", tier: Tier::Standard, words: space_astronomy::WORDS },
    Category { name: "Sports", tier: Tier::Standard, words: sports::WORDS },
    Category { name: "Superheroes & Comics", tier: Tier::Standard, words: superheroes::WORDS },
    Category { name: "The Zoo", tier: Tier::Standard, words: the_zoo::WORDS },
    Category { name: "Tools", tier: Tier::Standard, words: tools::WORDS },
    Category { name: "Toys", tier: Tier::Standard, words: toys::WORDS },
    Category { name: "Vehicles", tier: Tier::Standard, words: vehicles::WORDS },
    Category { name: "Video Games", tier: Tier::Standard, words: video_games::WORDS },
    Category { name: "War Films", tier: Tier::Standard, words: war_films::WORDS },
    Category { name: "Weather", tier: Tier::Standard, words: weather::WORDS },
    Category { name: "Weddings", tier: Tier::Standard, words: weddings::WORDS },
    Category { name: "Western", tier: Tier::Standard, words: western::WORDS },
    Category { name: "World Events", tier: Tier::Standard, words: world_events::WORDS },
    Category { name: "Anatomy", tier: Tier::Challenging, words: anatomy::WORDS },
    Category { name: "Archaeology", tier: Tier::Challenging, words: archaeology::WORDS },
    Category { name: "Architecture", tier: Tier::Challenging, words: architecture::WORDS },
    Category { name: "Astrology/Zodiac", tier: Tier::Challenging, words: astrology_zodiac::WORDS },
    Category { name: "Business", tier: Tier::Challenging, words: business::WORDS },
    Category { name: "Chemistry Elements/Terms", tier: Tier::Challenging, words: chemistry::WORDS },
    Category { name: "Computer Science", tier: Tier::Challenging, words: computer_science::WORDS },
    Category { name: "Computers", tier: Tier::Challenging, words: computers::WORDS },
    Category { name: "Cooking Techniques", tier: Tier::Challenging, words: cooking_techniques::WORDS },
    Category { name: "Corporate Life", tier: Tier::Challenging, words: corporate_life::WORDS },
    Category { name: "Cryptic/Obscure Adjectives", tier: Tier::Challenging, words: cryptic_adjectives::WORDS },
    Category { name: "Cryptography", tier: Tier::Challenging, words: cryptography::WORDS },
    Category { name: "Economics & Finance", tier: Tier::Challenging, words: economics_finance::WORDS },
    Category { name: "Etymology/Word Roots", tier: Tier::Challenging, words: etymology_word_roots::WORDS },
    Category { name: "Forensics", tier: Tier::Challenging, words: forensics::WORDS },
    Category { name: "Geology/Minerals", tier: Tier::Challenging, words: geology_minerals::WORDS },
    Category { name: "Grammar/Linguistics", tier: Tier::Challenging, words: grammar_linguistics::WORDS },
    Category { name: "Heraldry", tier: Tier::Challenging, words: heraldry::WORDS },
    Category { name: "History", tier: Tier::Challenging, words: history::WORDS },
    Category { name: "Legal Terms", tier: Tier::Challenging, words: legal_terms::WORDS },
    Category { name: "Literary Devices", tier: Tier::Challenging, words: literary_devices::WORDS },
    Category { name: "Medical Terminology", tier: Tier::Challenging, words: medical_terminology::WORDS },
    Category { name: "Music Theory", tier: Tier::Challenging, words: music_theory::WORDS },
    Category { name: "Mycology (Fungi)", tier: Tier::Challenging, words: mycology::WORDS },
    Category { name: "Mythology", tier: Tier::Challenging, words: mythology::WORDS },
    Category { name: "Nautical Terms", tier: Tier::Challenging, words: nautical_terms::WORDS },
    Category { name: "Paleontology", tier: Tier::Challenging, words: paleontology::WORDS },
    Category { name: "Philosophy", tier: Tier::Challenging, words: philosophy::WORDS },
    Category { name: "Physics", tier: Tier::Challenging, words: physics::WORDS },
    Category { name: "Psychology", tier: Tier::Challenging, words: psychology::WORDS },
    Category { name: "The Trades", tier: Tier::Challenging, words: trades::WORDS },
    Category { name: "Types of Government", tier: Tier::Challenging, words: types_of_government::WORDS },
    Category { name: "Weaving/Textiles", tier: Tier::Challenging, words: weaving_textiles::WORDS },
];
