// Generated by scripts/gen_dictionary.py -- do not hand-edit.
use std::sync::OnceLock;

static RAW: &str = include_str!("dictionary.txt");
static DICTIONARY: OnceLock<Vec<&'static str>> = OnceLock::new();

pub fn dictionary() -> &'static [&'static str] {
    DICTIONARY.get_or_init(|| RAW.lines().collect())
}
